### ISSUE TITLE
Two Sum

### ISSUE THREAD

**Issue by rldnrl** [rldnrl/java-coding-interview#1]
# 📝 요구사항 분석

- `target`을 만드는 `nums`의 `index`들을 출력한다.
- [Two Sum](https://leetcode.com/problems/two-sum/)

# 🎯 접근 방법

- 모든 `Index`에 대해서 `HashTable`을 만든다.
    - Key: Element
    - Value: Index
- 다음 조건을 만족시킬 때 `return` 하도록한다.
    - `HashTable`에 `target - element`가 있고
    - `HashTable`의 `target - element`의 값이 `index`가 아닐 경우
- 그렇지 않으면 for-loop 진행.

# ✅ To-Do

- [x]  Key가 Element 하고 Value가 Index로 하는 `HashTable`을 만든다.
- [x]  `nums.length`만큼 반복한다.
    - [x]  `result[0]`에 `index`를 넣는다.
    - [x]  `HashTable`에 `target - element`가 있고, `target - element`의 값이 `index`가 아닐 경우 `result[1]`에 HashMap에 `target - element`의 값을 넣는다. 그리고 반복문을 빠져나온다.
    - [x]  그렇지 않은 경우 `result[0] = 0`으로 초기화 한다.
- [x]  `result`를 `return` 한다.
