### ISSUE TITLE
First Unique Character in a String

### ISSUE THREAD

**Issue by rldnrl** [rldnrl/java-coding-interview#2]
# 📝 요구사항 분석

- 인자로 `string`이 주어지고 첫번째로 유일한 문자의 `index`를 출력하는 문제
- [First Unique Character in a String](https://leetcode.com/problems/first-unique-character-in-a-string/)

# 🎯 접근 방법
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/81848094/202900443-adb2c730-99dc-4c23-b53f-80047f20885c.png">

1. `s`를 순회한다.
2. Key가 `Character`, Value가 `Integer`인 `HashMap`을 만든다.
3. Value에 `count`를 저장한다.
4. s를 순회한다.
    1. `HashMap`의 `s.charAt(i)`가 `1`이 되면 `index`를 반환한다.
    2. 순회가 끝나면 유일한 문자가 없는 것이므로 `-1`를 반환한다.

# ✅ To-Do

- [x]  `HashMap`을 선언한다.
- [x]  `s`를 순회하면서
    - [x]  `HashMap`에 해당 문자의 `count`를 저장한다.
- [x]  `s`를 순회하면서
    - [x]  `HashMap`의 `s.charAt(i)`가 `1`이 되면 `index`를 반환한다.
    - [x]  순회가 끝나면 유일한 문자가 없는 것이므로 `-1`를 반환한다.
