### ISSUE TITLE
Valid Parentheses

### ISSUE THREAD

**Issue by rldnrl** [rldnrl/java-coding-interview#3]
# 📝 요구사항 분석

- 괄호의 짝을 맞추는 문제
- [Valid Parentheses](https://leetcode.com/problems/valid-parentheses/)

# 🎯 접근 방법

- Stack을 이용한다.
- Map을 만든다.
    - Key: 닫는 괄호
    - Value: 여는 괄호
- 주어진 괄호를 반복한다.
    - 여는 괄호를 Stack에 넣는다.
    - `stack.length === 0 || Map.get(닫는 괄호) !== stack.pop()` → `return false`
- 최종적으로 `return stack.length === 0`

# ✅ To-Do

- [x]  Map을 만든다.
    - Key: 닫는 괄호
    - Value: 여는 괄호
- [x]  주어진 괄호를 반복한다.
    - [x]  여는 괄호를 Stack에 넣는다.
    - [x]  `stack.length === 0 || Map.get(닫는 괄호) !== stack.pop()` → `return false`
- [x]  최종적으로 `return stack.length === 0`
